# Build and release

name: Release

# Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Define the build job
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   # Check out to $GITHUB_WORKSPACE

    - name: Install Xtensa Cross-compiler
      run: |
        export XTENSA=$HOME/src
        mkdir -p $XTENSA
        cd $XTENSA
        wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
        export PATH="$PATH:$XTENSA/xtensa-esp32-elf/bin"

    - name: Install Espressif IDF
      run: |
        export ESPIDF=$HOME/src/espressif/esp-idf
        mkdir -p $ESPIDF
        cd $ESPIDF
        git clone https://github.com/espressif/esp-idf.git $ESPIDF
        git checkout 9e70825d1e1cbf7988cf36981774300066580ea7
        git submodule update --init --recursive
