# Build and release

name: Release

# Triggers the workflow on push events but only for the master branch
on:
  pull_request:
    
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Define the build job
  build:
    env:
      ESPIDF: /home/runner/src/espressif/esp-idf
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   # Check out to $GITHUB_WORKSPACE

    - name: Collect Espressif IDF
      run: |
        mkdir -p $ESPIDF
        cd $ESPIDF
        git clone https://github.com/espressif/esp-idf.git $ESPIDF
        git checkout 4c81978a3e2220674a432a588292a4c860eef27b
        git submodule update --init --recursive
        
    - name: Install Espressif IDF Python Dependancies
      uses: BSFishy/pip-action@v1
      with:
        requirements: /home/runner/src/espressif/esp-idf/requirements.txt

    - name: Install Espressif IDF
      run: |
        cd $ESPIDF
        ls -l
        ./install.sh
        cd micropython/ports/esp32
        source $ESPIDF/export.sh
